config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index'
  post 'tasks', to: 'tasks#create'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: :task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    new_task = Task.new(task_params)
    new_task.save
    redirect_to tasks_path
  end

  def show
    # @task = Task.find(params[:id])
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="container">
  <%= form_for(@task) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :details %>
    <%= f.text_field :details%>
    <%= f.label :completed %>
    <%= f.text_field :completed %>
    <%= f.submit %>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<h1>Edit <%= @task.title %></h1>

<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>
<ul>
  <% @tasks.each do |task| %>
    <li>
      <%= link_to(task.title, task_path(task.id)) %>
    </li>
  <% end %>
</ul>
<%= link_to "new task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>Enter a new task</h1>
<br>
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details%>
  <%= f.submit %>
<% end %>

<%= link_to "Back to tasks", task_path %>

app/views/tasks/show.html.erb
<h1>Your task</h1>
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>
<%= link_to "Tasks", tasks_path %>
<%= link_to "Edit", edit_path %>
<%= link_to "Delete", task_path(@task), method: :delete, data: { confirm: "Are you sure?" } %>